### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '6,6'

### ISSUE THREAD

**Issue by evayfang2019** [farhangus/sniffle2_plot#1]
Hi, farhangus
when i ran:
`python3 sniffles2_plots.py -i ./tmp_samples/sample_merged.vcf -o ./test`
then reported:
./tmp_samples/sample_merged
Traceback (most recent call last):
  File "xxx/sniffle2_plot/vcf_visulaizer.py", line 31, in <module>
    main()
  File "xxx/sniffle2_plot/vcf_visulaizer.py", line 26, in main
    multi_visulaizer(input_vcf_file, output_path)
  File "xxx/sniffle2_plot/src/multi_vcf_visualizer.py", line 19, in multi_visulaizer
    SV_site.sv_sites_per_genome()
  File "xxx/sniffle2_plot/src/sv_sites_per_genome.py", line 36, in sv_sites_per_genome
    obj = VCFLineSVPopulation(line)
  File "xxx/sniffle2_plot/src/vcf_line_parser.py", line 213, in __init__
    self.get_genotype(FORMAT, sample_header_names)
  File "xxx/sniffle2_plot/src/vcf_line_parser.py", line 267, in get_genotype
    sample_gt.set_dr(gt_value)
  File "xxx/sniffle2_plot/src/vcf_line_parser.py", line 148, in set_dr
    self.dr = int(this_dr)
ValueError: invalid literal for int() with base 10: '6,6'

Sniffle2_plot might not be suitable for handling my VCF file at the moment, although it was also generated via sniffles.

**Comment by farhangus** [comment]
Dear evayfang2019,
Thanks for your message,  I will check it and get back to you. If possible,
may i have the VCF file for checking purposes.
Best regards

**Comment by evayfang2019** [comment]
Hi, farhangus
Thanks for your reply. Please check the vcf file.
Best regards
[evayfang2019.zip](https://github.com/farhangus/sniffle2_plot/files/12384995/evayfang2019.zip)

**Comment by farhangus** [comment]
Dear Evay,
Thanks for sending the file,I ran the program on file and the output is
attached. Will you please pull the package and rerun it. Please let me know
if there is any issue.
Command " python3 sniffles2_plots.py -i tmp1/evayfang2019.vcf -o tmp3"
Best regards,
Farhang

**Comment by evayfang2019** [comment]
Dear Farhang,
I've rerun the program and it's running smoothly.
Thank you and your outstanding works.
Best regards,
Evay

**Comment by farhangus** [comment]
Dear Evay,
You are most welcome, and thanks for your feedback.
Best regards,
Farhang
