### ISSUE TITLE
no main function defined in the sniffles2-plot/__main__.py (?!)

### ISSUE THREAD

**Issue by amnghn** [farhangus/sniffle2_plot#14]
Hi,
I asked our HPC support team to install sniffles2_plot, but they got back to me with the message below: 

> unfortunately there is no main function defined in the `sniffles2-plot/__main__.py` file, thus the program cannot be run due to an import error. Please report the issue to the devs and re-submit the installation request as soon as the problem is fixed.

Could you please confirm whether `__main__.py` is functional or not?

**Comment by farhangus** [comment]
Dear Amin,

Yes, the __main__.py file is functional. You can install the software using pip with the following command:

pip install sniffles2-plot

This will install the latest version of Sniffles2_plot, which includes the necessary __main__.py file for execution. If you encounter any issues during installation or execution, please let us know so we can assist you further.

**Comment by amnghn** [comment]
Hi @farhangus 
It worked, Thanks a lot.
