### ISSUE TITLE
N={SAMPLES} in src/size_distribution.py, why the N displays SV number not sample?

### ISSUE THREAD

**Issue by jingydz** [farhangus/sniffle2_plot#6]
![image](https://github.com/farhangus/sniffle2_plot/assets/45711930/ad20480b-485d-41d5-a058-a04d03b8c9e2)
src/size_distribution.py
SAMPLES = 0
        global SAMPLES
...
            for line in lines:
                if line[0] != "#":
                    obj = VCFLineSV(line)
                    if obj.ERROR:
                        continue
                    SAMPLES += 1
...
        text = f"N={SAMPLES}"
...
the N refers to sample or number?

**Comment by farhangus** [comment]
HI, The N refers ot the number.
