### ISSUE TITLE
hard-coded path causing error

### ISSUE THREAD

**Issue by jeremymchacon** [farhangus/sniffle2_plot#8]
Hello,

I installed sniffle2_plot with pip into a conda environment. When I try to run it, I get:

```

python3: can't open file 'src/sniffles2_plot/cli/vcf_visulaizer.py': [Errno 2] No such file or directory

```

I think the issue is because of hard-coded paths like so:

```

 f"python3 src/sniffles2_plot/cli/vcf_visulaizer.py -i {input_file_path} -o {output_file_path}"

```

For now I will get around it by calling vcf_visulaizer directly, but wanted to let you know.

Best,

Jeremy

**Comment by farhangus** [comment]
Thanks for letting me know, the issue is already solved and will  be updated in the next release
